{
  "hash": "9709989cbc558d9abf7171dd205edbb5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Discrete-Event Simulation for Cost-Effectiveness Analysis with Resource Contention\"\nsubtitle: \"A model-by-model build of the Sick-Sicker model, from natural history to a screening decision under capacity contention\"\nauthor:\n  - \"Shawn Garbett\"\n  - \"John Graves\"\ndate: today\nabstract: >\n  We build a discrete-event simulation (DES) of the Sick-Sicker cost-effectiveness model one idea\n  at a time, then use it to evaluate a concrete policy decision from a lower-middle-income country:\n  whether to replace an expensive, high-accuracy molecular screening test (the standard of care)\n  with a cheaper, lower-accuracy field test that reaches far more people. Ignoring downstream\n  capacity, the field test is dominant — cheaper *and* more effective. But its referral volume\n  overwhelms a fixed confirmatory-diagnostic bottleneck, and patients progress untreated while they\n  queue. We show that the way the queue is modelled changes the recommendation: an exogenous (fixed)\n  wait misses the problem, while two faithful endogenous designs — an occupancy-coupled registry\n  event (A) and a claim-ticket companion (B) — drift the cost-effectiveness result out of the\n  dominant quadrant. Throughout we use common random numbers to make the comparison precise.\n---\n\n\n\n::: {.callout-note}\n## How to read this document\nThis is a *teaching build*. Each section adds **one** idea to the model. The full, tested code for\neach step lives in a companion `model-N.R` file that we `source()` and run; inline we surface only\nthe **delta** — the new or changed function — heavily commented. Design rationale and the verified\n`simmer` semantics behind the contention designs are in [`methodology.md`](methodology.md); the\nsection-by-section plan is in [`PLAN.md`](PLAN.md).\n:::\n\n# Orientation\n\nThis is the on-ramp, not the textbook. Before we build anything, we settle three\nthings: how to *read* a discrete-event simulation (DES) if your native language is\ncost-effectiveness analysis (CEA), the two pictures we will lean on for the rest of\nthe document, and the one capability that makes the whole exercise worth the trouble —\ncontention. If a section here feels obvious, skip it; we return to each idea in code\nlater.\n\n## Reading a DES as a CEA modeller\n\nA DES is built out of a small handful of `simmer` nouns, and every one of them maps\ncleanly onto something you already think about. The translation is worth committing\nto memory, because the rest of the build is just these nouns acquiring detail.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: The DES-to-CEA terminology map. The two resource rows are the whole story of this document.\n\n|simmer term                 |CEA reading                                                                     |\n|:---------------------------|:-------------------------------------------------------------------------------|\n|trajectory                  |one patient's life history                                                      |\n|environment (`env`)         |the health system the patients move through                                     |\n|attribute                   |a patient's current health state (0 = H, 1 = S1, 2 = S2) and flags              |\n|event / `timeout`           |a transition firing after some sampled time                                     |\n|resource (capacity = `Inf`) |a **costed counter** — a tally we seize/release only to integrate time-in-state |\n|resource (capacity = `c`)   |a **genuinely finite, contended** resource patients must queue for              |\n|arrivals ledger             |the per-patient, per-state record we value *after* the run                      |\n\n\n:::\n:::\n\n\nThe two resource rows are the fork in the road. For models 1 through 7 every\n\"resource\" is a **counter** with `capacity = Inf`: it can never be full, so seizing\nit is instantaneous and exists purely so we can measure how long each patient spent\nin health state 0 (H), 1 (S1), or 2 (S2) and attach costs and QALYs to that time.\nNothing is ever contended. From model 8 onward we introduce a resource with a real,\nfinite capacity `c` ≪ N — a fixed number of treatment slots — and now seizing it can\n*fail*, because someone else is already in the chair. That single change is what DES\nis for, and also where it bites back; the rest of Part II and the two designs that\nfollow are about getting it right.\n\n::: {.callout-note}\n## The vocabulary we reuse without re-explaining\nHealth states are **0-indexed numerics** throughout: `0 = H` (healthy),\n`1 = S1` (sick), `2 = S2` (sicker). A **counter** is a `capacity = Inf` resource used\nonly for time-in-state costing — never for contention — *unless we deliberately\nconstrain it*. When we do constrain one, we say so loudly.\n:::\n\n## The car race: an intuition for contention\n\nPicture a stock-car race. Each **driver** is a patient; the **track** is the health\nsystem; **laps completed** are person-years lived. So far this is just a moving\npopulation — drivers lap independently and nothing ties one car's fate to another's.\n\n![A field of drivers on the track. On its own, a moving population: each car laps independently, nobody waits on anybody.](../figures/car-race.png){#fig-car-race width=55%}\n\nContention enters when a car needs the **pit crew**. There is one mechanic (or `c`\nmechanics), and a car that pulls in while the mechanic is busy with someone else must\n*wait* — losing laps, possibly crashing out — until a bay frees up. Waiting for a\nmechanic is exactly waiting for a treatment slot: the resource is finite, the queue\nis real, and crucially **the race does not pause for the cars in line.**\n\n![One mechanic, one bay. A car that arrives while the bay is occupied must queue — and the clock keeps running while it waits.](../figures/mechanic.png){#fig-mechanic width=45%}\n\nWhen demand for the bay outstrips supply, you get **congestion** — a pack of cars\nbacked up behind a bottleneck, each one's wait determined by how many are ahead of it.\nThat endogenous wait — *my* delay depends on *everyone else's* demand — is the thing a\npatient-by-patient model cannot fake, and the thing this whole document is built to\ncapture faithfully.\n\n![Congestion: when arrivals outpace the bay, waits stack up and each car's delay depends on the whole field's demand. This is the contention DES must model.](../figures/congestion.png){#fig-congestion width=50%}\n\n::: {.callout-tip}\nThe two pillars of intuition we reuse throughout: the **car race** (patients =\ndrivers, waiting for a mechanic = waiting for a treatment slot) and the **Petri net**\n(places, transitions, tokens, arcs), introduced next.\n:::\n\n## The Petri-net visual grammar\n\nWhen we need to draw a model rather than describe it, we use a Petri net. It has\nexactly four symbols, and we use them consistently from here to the end:\n\n- **Place** — a labelled circle: a state a patient can occupy (H, S1, S2, or \"in\n  treatment\").\n- **Token** — a filled dot sitting inside a place: one patient, here, now.\n- **Transition** — a bar: an event that moves a token from one place to another\n  (incidence, recovery, death, seizing a slot).\n- **Arc** — an arrow connecting a place to a transition or back: who can flow where.\n\n![The four symbols. A **place** (circle) holds **tokens** (dots) — one dot, one patient. **Transitions** (bars) move tokens along **arcs** (arrows).](../figures/petri-place.png){#fig-petri-place width=22%}\n\nContention has a precise Petri-net signature. A finite resource is a place with a\n**limited number of token slots**. When more patients want it than it can hold, the\nsurplus tokens pile up *outside* the place — a visible **queue** waiting for the\ntransition to fire. That picture is the difference between a counter and a contended\nresource, drawn:\n\n![Contention in Petri-net form: the resource place is **full** (right), so newly arriving tokens form a **queue** (left) and cannot enter until a slot frees. An `Inf`-capacity counter never fills, so it never produces this queue.](../figures/petri-token-queue.png){#fig-petri-token-queue width=55%}\n\nThe full Sick-Sicker model with one constrained treatment resource is our target\npicture. Note the shaded \"Constrained resource\" box: a `Seize` transition gated by a\nfinite-capacity treatment place, a `Release` arc returning the slot, and — the part\nthat makes this hard — the disease transitions (death, progression, recovery,\nend-of-horizon) that **must keep firing while a patient is in the queue.** Everything\nbetween here and Part III is about reaching this diagram without breaking it.\n\n![The target: the full Sick-Sicker ladder (H ⇄ S1 → S2, each with death and an end-of-horizon transition) plus a **constrained treatment resource** (shaded) with explicit Seize and Release. The disease transitions never stop firing — including for a patient waiting on the slot.](../figures/petri-model6.png){#fig-petri-model6 width=92%}\n\n## Why DES, and not Markov or microsimulation\n\nA cohort Markov model and a patient-level microsimulation can both reproduce the\n*natural history* of Sick-Sicker perfectly well — states, transitions, costs, QALYs.\nFor models 1 through 9, DES buys us little a microsimulation would not. So why pay for\nDES at all? Two things only DES gives cleanly:\n\n1. **Queues and contention.** In a Markov or microsimulation model each patient's\n   transition probabilities are fixed in advance; one patient's trajectory cannot\n   depend on how many *other* patients are currently competing for a scarce resource.\n   The endogenous wait of @fig-congestion — *my* delay is a function of the whole\n   population's demand right now — is structurally outside what those frameworks\n   express. It is exactly what DES exists to model.\n2. **Exact event times.** DES works in continuous time: every transition fires at a\n   precise, sampled instant, not at a fixed cycle boundary. That removes cycle-length\n   bias entirely (no half-cycle correction), and it is what lets a contended resource\n   be enforced *to the instant* a slot frees rather than to the nearest cycle.\n\nSo the honest framing for the build ahead: models 1–9 use DES as a clean, exact-time\nmicrosimulation; the payoff that justifies the machinery only arrives at model 10, when\na downstream resource finally becomes finite and patients must queue for it.\n\n## The cost of DES: a bouncer at an empty venue\n\nDES is not free. Its event-driven engine — sample every competing time, take the\n`argmin`, fire, reschedule — carries bookkeeping overhead that a vectorised cohort or\nmicrosimulation does not. Empirically, runtime grows roughly **O(n log n)** in the\nnumber of patients, and the constant is not small: the same Sick-Sicker model in\n`simmer` is orders of magnitude slower than a base-R or `data.table` implementation,\nwith the gap widening sharply as N grows.\n\n![Wall-clock cost of the same Sick-Sicker model three ways. `simmer`'s event engine (blue) climbs steeply with N; base-R and `data.table` stay near the floor. DES is the bouncer you only need when there's actually a queue.](../figures/des_versus_dt.png){#fig-des-vs-dt width=60%}\n\nThe lesson is one of fit-for-purpose. Running `simmer` on the *unconstrained* natural\nhistory is like hiring a bouncer for an empty venue — paying for crowd control when\nthere is no crowd to control. You bring in DES precisely when there *is* a queue: a\ngenuinely finite resource that patients contend for. For everything before that, a\ncheaper engine would do; we use DES throughout only so that the single mechanism\nthat *does* need it slots into machinery the reader already understands. (Practically,\nthis also caps N: keep cohorts modest in this document and quote production-scale\nnumbers in prose.)\n\n::: {.callout-note}\n## What we build, and in what order\n**Part I** builds the cost-effectiveness model one idea per section — the engine\n(model 1), valuation as a separate pass (model 2), the first competing risk\n(model 3), the first disease state (model 4), recovery (model 5), and the full\nSick-Sicker ladder (model 6). **Part II** introduces the policy decision: model 7\nadds a one-time *screening* program and establishes the molecular test as the\nstandard of care; model 8 introduces the cheaper *field test* as a comparator and —\nignoring downstream capacity — finds it dominant (cheaper *and* more effective).\nModel 9 inserts an *exogenous* confirmatory wait and shows it gives false reassurance.\n**Part III** makes the confirmatory bottleneck genuinely finite and models the queue\n*endogenously*, two ways: the occupancy-coupled registry event (**A**, model 10) and\nthe claim-ticket companion (**B**, model 11). **Part IV** compares them, traces how\ncontention drifts the cost-effectiveness result out of the dominant quadrant, and\ncloses with guidance and limitations. Each section adds exactly one new idea; we\nreference earlier ones rather than repeat them. Throughout we lean on **common random\nnumbers** so that the difference between two strategies is signal, not noise.\n:::\n\n# Part I — Building the cost-effectiveness model\n\n## Model 1 — the engine and the empty patient\n\nEvery later model reuses the same six-part contract — `counters`, `initialize_patient()`,\n`cleanup_on_termination()`, `terminate_simulation()`, an `event_registry`, and a `des_run()` wrapper.\n`main_loop.R` is the hand-rolled next-event engine (`event_registry` → `next_event()` = argmin of\nsampled times → `branch |> rollback`); we treat it as a black box and never edit it. At this stage\n`simmer` is only a timeout/tally engine: the `time_in_model` \"resource\" has capacity `Inf` and exists\npurely to record time-in-state for later costing — **not** to model contention. (That distinction is\nthe whole setup for Approaches A and B.)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(1)\nsource(here::here(\"R/model-1.R\"), chdir = TRUE)   # defines the 6-part contract + a single trivial \"Terminate at horizon\" event\narrivals <- des_run(inputs)\nhead(arrivals)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"start_time\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"end_time\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"activity_time\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"resource\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"replication\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"patient0\",\"2\":\"0\",\"3\":\"30\",\"4\":\"30\",\"5\":\"time_in_model\",\"6\":\"1\",\"_rn_\":\"1\"},{\"1\":\"patient1\",\"2\":\"0\",\"3\":\"30\",\"4\":\"30\",\"5\":\"time_in_model\",\"6\":\"1\",\"_rn_\":\"2\"},{\"1\":\"patient2\",\"2\":\"0\",\"3\":\"30\",\"4\":\"30\",\"5\":\"time_in_model\",\"6\":\"1\",\"_rn_\":\"3\"},{\"1\":\"patient3\",\"2\":\"0\",\"3\":\"30\",\"4\":\"30\",\"5\":\"time_in_model\",\"6\":\"1\",\"_rn_\":\"4\"},{\"1\":\"patient4\",\"2\":\"0\",\"3\":\"30\",\"4\":\"30\",\"5\":\"time_in_model\",\"6\":\"1\",\"_rn_\":\"5\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe single event in the registry is the trivial one:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# THE DELTA: the registry holds exactly one (deterministic) event so the engine can be seen in\n# isolation before any clinical events exist.\nevent_registry <- list(\n  list(name          = \"Terminate at time horizon\",\n       attr          = \"aTerminate\",\n       time_to_event = function(inputs) inputs$horizon - now(env),\n       func          = terminate_simulation,\n       reactive      = FALSE)\n)\n```\n:::\n\n\n::: {.callout-warning}\n## The `function()`-callback gotcha\n`set_attribute(\"AgeInitial\", sample(20:30, 1))` samples **once at build time** (all patients get the\nsame value); `set_attribute(\"AgeInitial\", function() sample(20:30, 1))` samples **per patient**. The\nsame rule governs per-patient wait and treatment-effect durations later — wrap them in `function()`.\n:::\n\n## Model 2 — valuation as a separate pass (costs, QALYs, discounting)\n\n**Objective:** put numbers on the run. Model 1 ended with an *arrivals ledger* — one row per patient per resource, recording when each patient seized and released `time_in_model`. That ledger is the only thing a DES run produces. It says nothing yet about money or quality of life. Model 2 adds the idea that turns a ledger into a cost-effectiveness result, and it is deliberately a small idea: **valuation is a separate pass over the ledger, not part of the run.**\n\nNothing in the engine changes. We do not touch `main_loop.R`, the `event_registry` still holds only the trivial terminate-at-horizon event, and patients still do nothing but exist for 30 years. The only new code is two functions — `cost_arrivals()` and `qaly_arrivals()` — that take the finished ledger and append columns to it. `des_run()` simply pipes its result through them on the way out.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(1)\nsource(here::here(\"R/model-2.R\"), chdir = TRUE)            # same 6-part contract as Model 1, plus cost_arrivals() + qaly_arrivals()\narrivals <- des_run(inputs)    # N = 5 patients, horizon = 30 years\nhead(arrivals)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"start_time\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"end_time\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"activity_time\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"resource\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"replication\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"cost\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"dcost\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"qaly\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"dqaly\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"patient0\",\"2\":\"0\",\"3\":\"30\",\"4\":\"30\",\"5\":\"time_in_model\",\"6\":\"1\",\"7\":\"0\",\"8\":\"0\",\"9\":\"30\",\"10\":\"19.893\",\"_rn_\":\"1\"},{\"1\":\"patient1\",\"2\":\"0\",\"3\":\"30\",\"4\":\"30\",\"5\":\"time_in_model\",\"6\":\"1\",\"7\":\"0\",\"8\":\"0\",\"9\":\"30\",\"10\":\"19.893\",\"_rn_\":\"2\"},{\"1\":\"patient2\",\"2\":\"0\",\"3\":\"30\",\"4\":\"30\",\"5\":\"time_in_model\",\"6\":\"1\",\"7\":\"0\",\"8\":\"0\",\"9\":\"30\",\"10\":\"19.893\",\"_rn_\":\"3\"},{\"1\":\"patient3\",\"2\":\"0\",\"3\":\"30\",\"4\":\"30\",\"5\":\"time_in_model\",\"6\":\"1\",\"7\":\"0\",\"8\":\"0\",\"9\":\"30\",\"10\":\"19.893\",\"_rn_\":\"4\"},{\"1\":\"patient4\",\"2\":\"0\",\"3\":\"30\",\"4\":\"30\",\"5\":\"time_in_model\",\"6\":\"1\",\"7\":\"0\",\"8\":\"0\",\"9\":\"30\",\"10\":\"19.893\",\"_rn_\":\"5\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe ledger now carries four new columns. `cost` and `dcost` are undiscounted and discounted cost; `qaly` and `dqaly` are undiscounted and discounted quality-adjusted life-years. Costs are still zero — there are no costed events yet, so `cost_arrivals()` is a placeholder that writes `0`. But the QALY columns are already meaningful: with nobody dying and everybody healthy, each patient accrues one QALY per year of time-in-model. Their undiscounted `qaly` is therefore `end_time - start_time = 30`, and their discounted `dqaly` is `19.893`.\n\nTwo things are worth pausing on. First, the QALY total is computed *from the ledger*, by subtracting the seize time of `time_in_model` from its release time — exactly the time-in-state accounting the capacity-`Inf` counter was built to support in Model 1. Second, because valuation is a pure function of the ledger, it is **re-derivable at any time**: change a cost in `inputs.R`, or change the discount rate, and you re-value the *same* run rather than re-simulating it. That separation is what lets later models keep one expensive stochastic run and value it under several costing assumptions cheaply.\n\n### The delta: two valuation functions\n\nThe whole of Model 2's new code is below. `qaly_arrivals()` is the part with content; `cost_arrivals()` is its still-empty twin, present so the shape is in place for Model 3 onward.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# THE DELTA: valuation runs AFTER the simulation, over the arrivals ledger.\n# des_run() ends with:  get_mon_arrivals(env, per_resource = TRUE) |> cost_arrivals(inputs) |> qaly_arrivals(inputs)\n\ncost_arrivals <- function(arrivals, inputs)\n{\n  arrivals$cost  <- 0   # No costed events yet — placeholder.\n  arrivals$dcost <- 0   # (discounted) likewise.\n  arrivals\n}\n\nqaly_arrivals <- function(arrivals, inputs)\n{\n  arrivals$qaly  <- 0\n  arrivals$dqaly <- 0\n\n  # One QALY per year spent in the model. Select the time_in_model rows...\n  selector <- arrivals$resource == 'time_in_model'\n\n  # ...undiscounted QALYs = elapsed time in that resource (release - seize):\n  arrivals$qaly[selector]  <- arrivals$end_time[selector] - arrivals$start_time[selector]\n\n  # ...discounted QALYs = the analytic integral of a discounted unit rate\n  #    over [start_time, end_time]; see discount_value() below.\n  arrivals$dqaly[selector] <- discount_value(1, arrivals$start_time[selector],\n                                                arrivals$end_time[selector])\n  arrivals\n}\n```\n:::\n\n\nThe pattern to carry forward: every future state contributes its rows to this same selector-and-fill idiom. Add a state, and you add (i) a `cost`/`dcost` line and (ii) a `qaly`/`dqaly` line that selects that state's rows and values the time spent there. Nothing about *how* the run unfolds is touched; only what we read off it afterwards.\n\n::: {.callout-note}\n## Continuous discounting, and why the integral form\n\nA health-economic convention discounts future value continuously rather than once at the end of each year. `discount.R`'s `discount_value()` does both jobs from one formula. Called with a single time point it returns a discounted *point* value; called with two it returns the *area under the discounted curve* between them — which is what we want for a QALY rate accruing over an interval.\n\nIt first converts the annual rate to a continuous rate, $r = -\\log(1 + 0.03)$, then integrates a constant unit rate:\n\n$$\n\\int_{t_A}^{t_B} e^{r t}\\,dt \\;=\\; \\frac{e^{r t_B} - e^{r t_A}}{r}.\n$$\n\nThis closed form is used deliberately in place of the naive `value / (1 + rate)^t`: subtracting two exponentials is numerically stable across long horizons, where repeated powering drifts. A few values, all reproducible:\n\n- `discount_value(1, 0)` $= 1$ — a unit at time zero is undiscounted.\n- `discount_value(1, 30)` $\\approx 0.412$ — a unit thirty years out is worth about 41p of a present unit.\n- `discount_value(1, 0, 1)` $\\approx 0.985$ — one QALY accrued *continuously* over the first year is worth slightly more than the naive end-of-year figure $1/1.03 \\approx 0.971$, because some of it accrues early when discounting bites less.\n- `discount_value(1, 0, 30)` $= 19.893$ — which is exactly the `dqaly` printed in the ledger above. The loop closes: the discounted lifetime QALY for a patient alive over $[0, 30]$ is the same integral, computed the same way.\n:::\n\n## Model 3 — the first competing risk (Death)\n\n**Objective:** give the patient a way to leave before the horizon. Until now the registry held a single, deterministic event — \"terminate at the horizon\" — so `next_event()` had nothing to choose between: every patient ran the full 30 years. We now add a *second* registry entry, a random death time, and that one addition is what first switches the engine on. With two events in play, `next_event()` becomes a genuine `argmin`: it samples a death time, compares it against the remaining time to the horizon, and the earlier of the two wins.\n\nThis is the first true *competing risk*. In Petri-net terms, the healthy place now has two transition bars draining it — one to the empty place ∅ (death), one to the end of the simulation — and the patient's token fires through whichever bar comes up first.\n\n![Model 3 as a Petri net: the healthy place **H** now has two competing transitions — a death bar draining to ∅ and the end-of-simulation bar at *t = T*. Whichever fires first removes the token.](../figures/petri-model2.png)\n\n### The event-per-file pattern\n\nEach clinical event lives in its own small file that defines two functions: a `time_to_event` (when, in years, might this happen) and a `func` (what to do to the trajectory if it does). Here that file is `event_death.R`, and the registry entry simply names the pair. Sourcing `model-3.R` pulls it in and appends the entry to `event_registry`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(3)\nsource(here::here(\"R/model-3.R\"), chdir = TRUE)                         # adds Death to the event registry\narrivals <- des_run(modifyList(inputs, list(N = 1000)))\n\n# A \"death\" row now appears in the ledger, alongside time_in_model:\narrivals |> count(resource)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"resource\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"death\",\"2\":\"145\"},{\"1\":\"time_in_model\",\"2\":\"1000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n\n# Some patients leave before the 30-year horizon -- their time_in_model truncates:\narrivals |>\n  filter(resource == \"time_in_model\") |>\n  summarise(n          = n(),\n            died_early = sum(end_time < 30 - 1e-6),\n            max_end    = max(end_time))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"n\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"died_early\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"max_end\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1000\",\"2\":\"145\",\"3\":\"30\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nTwo things have changed in the ledger. First, a new `death` resource appears — these are the patients who hit the death transition, each marked exactly once. Second, for those patients `time_in_model` no longer runs the full horizon: it `end_time`s at the moment of death. Survivors still cap at 30. (At a production *N* the early-death fraction settles near 14%, consistent with the secular rate `r.HD = 0.005` compounded over 30 years.)\n\n### The delta: `event_death.R`\n\nThe new file is short. Note the two pieces — a draw and a force-terminate.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# THE DELTA: a self-contained event. A draw for *when*, a handler for *what*.\n\n# When would this patient die a secular death? A single exponential draw.\n# (A deliberately crude mortality model -- it is the H->D reference rate the\n#  sicker states will later scale up via hazard ratios.)\nyears_till_death <- function(inputs)\n{\n  rexp(1, inputs$r.HD)\n}\n\n# What happens if Death wins the argmin? Mark the counter and force-terminate.\ndeath <- function(traj, inputs)\n{\n  traj |> branch(\n    function() 1,            # always take arm 1 -- this is not a real choice\n    continue = c(FALSE),     # ...and do NOT continue the parent trajectory\n    trajectory(\"Death\") |>\n      mark(\"death\")     |>   # tally the death (must be listed in `counters`)\n      terminate_simulation() # release time_in_model and end the patient\n  )\n}\n```\n:::\n\n\nAnd the one-line registry addition that activates the competition:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# The second entry. Now next_event() has two candidate times to compare.\nevent_registry <- list(\n  list(name          = \"Terminate at time horizon\",\n       attr          = \"aTerminate\",\n       time_to_event = function(inputs) inputs$horizon - now(env),\n       func          = terminate_simulation,\n       reactive      = FALSE),\n  list(name          = \"Death\",                 # <- NEW\n       attr          = \"aDeath\",\n       time_to_event = years_till_death,\n       func          = death,\n       reactive      = FALSE)\n)\n```\n:::\n\n\n::: {.callout-note}\n## The `branch(continue = FALSE)` force-terminate idiom\nKilling a patient is the one place we use `branch()` for something other than branching. The selector `function() 1` always picks the single sub-trajectory, so this is not a real fork — it is a syntactic trick. The work is done by `continue = FALSE`, which tells `simmer` *not* to resume the parent trajectory after the sub-trajectory finishes. Without it, the patient would tally a death and then sail on through the rest of their event loop. The sub-trajectory itself just `mark()`s the `death` counter (which must appear in `counters`, exactly as `time_in_model` does) and calls `terminate_simulation()` to release the held counter cleanly. You will see this same `branch(continue = FALSE)` pattern every time a patient leaves the model for good.\n:::\n\nWith a real competing risk in place, `next_event()`'s `argmin` is finally earning its keep. The next model adds the first *disease* state, so that the set of candidate events — and the death hazard itself — depends on where the patient currently sits.\n\n## Model 4 — the first disease state, and reactive events\n\n**Objective:** give the patient a place to *be* other than healthy or dead. Until now a patient was a token sitting in `healthy` until either the horizon or Death pulled them out. We now add the first disease state, **S1** (mildly sick), and with it the first thing that makes a microsimulation feel alive: a hazard that *changes when the patient's state changes*. That is what `reactive = TRUE` is for.\n\nWe continue to track state with the `State` attribute, **0-indexed**: `0 = H` (healthy), `1 = S1`. (Model 6 adds `2 = S2`.) The patient now has two competing risks racing at all times — Death and onset of S1 — plus the ever-present horizon. `next_event()` takes the argmin, exactly as before; nothing in `main_loop.R` changes.\n\n![Model 4 as a Petri net: a new **S1** place, with an onset transition (H → S1) and a state-dependent death transition firing from both H and S1.](../figures/petri-model4.png)\n\n### The four moving parts\n\n**1. The new state, as an attribute and as a counter.** Becoming sick is a transition that flips the `State` attribute from `0` to `1`, releases the `healthy` counter, and seizes the `sick1` counter. The counter swap is what later lets the valuation pass integrate time-in-state (Model 2's machinery, unchanged): every patient leaves *one row per state they occupied*.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# THE DELTA (event_sick1.R): onset is only possible from Healthy. From any other\n# state we return a time past the horizon, which disables the transition.\nyears_till_sick1 <- function(inputs)\n{\n  state <- get_attribute(env, \"State\")\n  if (state == 0)                 # 0 => Healthy: onset can happen\n    rexp(1, inputs$r.HS1)         #   draw an onset time at rate r.HS1\n  else\n    inputs$horizon + 1            # already sick (or worse): never fires\n}\n\nsick1 <- function(traj, inputs)\n{\n  traj                      |>\n  set_attribute(\"State\", 1) |>    # 1 => S1; the state flip is the whole point\n  release(\"healthy\")        |>    # stop accruing the H tally...\n  seize(\"sick1\")                  # ...start accruing the S1 tally\n}\n```\n:::\n\n\n**2. A state-dependent death hazard.** This is the clinically important part: sick patients die faster. The death event now reads the patient's state and multiplies the base rate by the S1 hazard ratio, `hr.S1D`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# THE DELTA (event_death2.R): death rate now depends on state.\nyears_till_death <- function(inputs)\n{\n  state <- get_attribute(env, \"State\")\n  rate  <- inputs$r.HD                       # base healthy mortality\n  if (state == 1) rate <- rate * inputs$hr.S1D   # in S1, die hr.S1D times faster\n  rexp(1, rate)\n}\n```\n:::\n\n\n**3. `reactive = TRUE` — the part that makes (2) work.** A hazard that depends on state is useless unless we *resample* it the moment the state changes. Consider a patient who, while healthy, drew a death time of (say) 40 years — comfortably past the horizon, so harmless. Then they become sick at year 7. Their mortality rate has just tripled, but that stale 40-year draw is still sitting in the `aDeath` attribute. If we did nothing, the patient would carry their *healthy* death time into a *sick* body.\n\nMarking an event `reactive = TRUE` in the registry tells the engine to throw away and re-draw that event's time after **every** transition. The mechanism lives in `main_loop.R`'s `process_events()` (we do not edit it) — at the tail of each event it re-runs `time_to_event()` for every reactive event:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# main_loop.R, inside process_events() — runs after every event fires:\nlapply(event_registry[sapply(event_registry, function(x) x$reactive)],\n  FUN = function(e) {\n    traj <- set_attribute(traj, e$attr,\n              function() { now(env) + e$time_to_event(inputs) })  # re-draw from NOW\n  })\n```\n:::\n\n\nBoth Death and Sick1 are `reactive = TRUE`; only the horizon (which never depends on state) stays `reactive = FALSE`. The rule of thumb: **if a `time_to_event()` reads `State`, its event must be reactive.**\n\n::: {.callout-warning}\n## Reactive resampling is a memoryless-only convenience\nRe-drawing the time from scratch at the transition is correct *because the underlying clocks are exponential* — `rexp` is memoryless, so a fresh draw from \"now\" is distributionally identical to having conditioned the original draw on survival to now. If you ever swap a `rexp` for a Weibull or a Gompertz, this shortcut silently introduces a bug: you would need to carry the *elapsed* time and condition on it, not re-draw afresh. Every clock in this build stays exponential precisely so that reactivity stays this cheap.\n:::\n\n**4. Per-state costs and utilities.** With two live states the valuation pass finally has something to discriminate. We extend `cost_arrivals()`/`qaly_arrivals()` with a selector for the new `sick1` rows, billing them at `c.S1` / `u.S1` instead of `c.H` / `u.H`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# THE DELTA: one more selector block per costed state (cost_arrivals / qaly_arrivals).\nselector <- arrivals$resource == 'sick1'\narrivals$cost[selector]  <- inputs$c.S1 *\n  (arrivals$end_time[selector] - arrivals$start_time[selector])\narrivals$qaly[selector]  <- inputs$u.S1 *\n  (arrivals$end_time[selector] - arrivals$start_time[selector])\n# (dcost / dqaly use discount_value() over the same interval, as in Model 2.)\n```\n:::\n\n\n### Run it\n\nSourcing `model-4.R` re-`source()`s the inputs and the engine, then redefines `des_run()` — so it cleanly replaces Model 3. We run a modest cohort and tally the rows by state. Every patient contributes one `time_in_model` row and one `healthy` row; the ~95% who fall sick add a `sick1` row; the third or so who die before the horizon add a `death` row.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(8)\nsource(here::here(\"R/model-4.R\"), chdir = TRUE)   # adds the State attribute, the reactive Sick1 event, and per-state cost/QALY\narrivals <- des_run(modifyList(inputs, list(N = 200)))\narrivals |>\n  count(resource) |>\n  knitr::kable(col.names = c(\"resource (state tally)\", \"rows\"),\n               caption = \"One row per state occupied: 200 patients, 190 fell sick, 65 died before the horizon.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: One row per state occupied: 200 patients, 190 fell sick, 65 died before the horizon.\n\n|resource (state tally) | rows|\n|:----------------------|----:|\n|death                  |   65|\n|healthy                |  200|\n|sick1                  |  190|\n|time_in_model          |  200|\n\n\n:::\n:::\n\n\n### The random-audit idiom\n\nA cohort summary tells you the model *ran*; it does not tell you the model is *right*. The single most useful validation habit in this whole build is to **pick one patient at random, sort their rows by time, and read their life story off the ledger** — checking that the chronology, the state sequence, and the per-state bills all make sense. We use this idiom in every model from here on.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(16)\none <- sample(unique(arrivals$name), 1)   # random-audit: one patient, picked blind\narrivals |>\n  filter(name == one) |>\n  arrange(start_time, end_time) |>        # read it top-to-bottom as a timeline\n  select(resource, start_time, end_time, cost, qaly) |>\n  knitr::kable(digits = 2, caption = paste(\"Audited life story:\", one))\n```\n\n::: {.cell-output-display}\n\n\nTable: Audited life story: patient191\n\n|resource      | start_time| end_time|    cost|  qaly|\n|:-------------|----------:|--------:|-------:|-----:|\n|healthy       |        0.0|      7.1|    0.00|  7.10|\n|time_in_model |        0.0|     26.7|    0.00|  0.00|\n|sick1         |        7.1|     26.7| 5882.92| 15.69|\n|death         |       26.7|     26.7|    0.00|  0.00|\n\n\n:::\n:::\n\n\nRead it as a sentence. `patient191` is healthy from year 0 to year **7.1** (one `healthy` row, costing `c.H` × 7.1 = 0 — healthy carries no disease-attributable cost in this calibration — while accruing 7.10 QALYs at `u.H` = 1.0). Onset of S1 fires at 7.1; from there to year **26.7** they are sick (one `sick1` row, billed at `c.S1` = 300 over 19.6 years ≈ 5,883, accruing 19.6 × `u.S1` = 15.69 QALYs). At **26.7** the (tripled, post-onset) death hazard finally wins, before the 30-year horizon. The `time_in_model` row spans the whole life, 0 to 26.7 — a free cross-check that the state rows tile the lifetime with no gaps and no overlap.\n\nThree things to verify on every audit, all of which hold here:\n\n- **Chronology is contiguous.** Each state's `end_time` is the next state's `start_time`; there are no gaps (uncounted time) and no overlaps (double-counted time). The `time_in_model` span equals the lifetime.\n- **The state sequence is legal.** `healthy → sick1 → death` is a path the registry actually permits. A patient showing `sick1` *before* `healthy`, or a `cost` on a `death`/`time_in_model` row, would betray a wiring bug.\n- **The per-state bills match the parameters.** A `sick1` row at `c.S1` not `c.H`; a QALY equal to duration × the right utility weight. Here the S1 QALYs (15.69) are visibly less than the S1 duration (19.6 years) — exactly the `u.S1` = 0.80 penalty for being sick.\n\n::: {.callout-tip}\nThe `arrange(start_time, end_time)` tie-break is why `time_in_model` (which also starts at 0) sorts *after* `healthy`: both begin at time 0, and the tie is broken by `end_time`. Sorting on the start time alone leaves zero-width events (`death`, fired at a single instant) and equal-start rows in an arbitrary order — sort on both, and the timeline reads cleanly every time.\n:::\n\nWith one disease state and a reactive, state-dependent death hazard in place, the model is a genuine two-state microsimulation. The next two steps make it a *recurrent* one — recovery back to health (Model 5), then progression onward to Sicker (Model 6) — but the audit idiom you just learned is the tool you will reach for to confirm each of them behaves.\n\n## Model 5 — recurrence (recovery S1 → H)\n\n**Objective:** add a single reactive event so that being sick is no longer a one-way trip. Until now the\ndisease has run downhill only — a healthy patient could fall sick (Model 4), but once in S1 the only exits\nwere death or the horizon. Real disease histories are rarely so tidy: people get better, relapse, and get\nbetter again. We make recovery a first-class transition, `S1 → H`, and in doing so turn the one-way cascade\ninto a **recurrent, bidirectional loop** between the two states.\n\nMechanically this is one more registry entry. The work we did in Model 4 — the `State` attribute, reactive\nresampling, per-state hazards and costing — already gives us everything we need to *receive* a returning\npatient. So this section is short by design: the engine does not change, only the registry grows.\n\n![The Petri net for Model 5. The recovery arc (S1 → H) closes the loop: a token in the S1 place can now flow back to H, not only onward to death or the horizon. Compare Model 4, where the only arcs leaving S1 pointed away from H.](../figures/petri-model5.png)\n\n### The delta: a fourth (reactive) registry entry\n\nRecovery needs the same two pieces every clinical event has had since Model 3: a `time_to_event()` that\nsamples *when* the patient would recover, and a `func()` that updates the patient when recovery *fires*.\nThe new file `event_healthy.R` supplies both, and `model-5.R` adds them as the fourth event in the\nregistry. Nothing else moves.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# THE DELTA (event_healthy.R): the mirror image of years_till_sick1().\n# Recovery is only possible *from* S1, so the time_to_event is STATE-GATED:\n# if the patient is not in S1, we return a time past the horizon, which makes\n# this transition effectively unreachable from any other state.\nyears_till_healthy <- function(inputs)\n{\n  state <- get_attribute(env, \"State\")\n  if (state == 1) {           # 1 => S1: recovery is on the table\n    rexp(1, inputs$r.S1H)     #   sample a recovery time at the S1 -> H rate\n  } else {\n    inputs$horizon + 1        # not in S1: return a time the engine will never pick\n  }\n}\n\n# When recovery fires, flip the patient back to Healthy and move the costing\n# token: release the 'sick1' counter, seize 'healthy'. (Same accounting move as\n# sick1(), run in reverse.)\nhealthy <- function(traj, inputs)\n{\n  traj                      |>\n  set_attribute(\"State\", 0) |> # 0 => H\n  seize('healthy')          |>\n  release('sick1')\n}\n\n# ...and in model-5.R the registry gains its fourth, reactive entry:\nevent_registry <- list(\n  # ... Terminate, Death, Sick1 as before ...\n  list(name          = \"Healthy\",\n       attr          = \"aHealthy\",\n       time_to_event = years_till_healthy,\n       func          = healthy,\n       reactive      = TRUE)   # resample on every state change, like its siblings\n)\n```\n:::\n\n\n::: {.callout-note}\n## The state-gated `time_to_event` idiom (`return horizon + 1`)\nThis is the pattern that lets one flat registry describe a state machine. Every reactive event is *always*\nin the registry, but each one **disables itself** when the current state cannot take that transition by\nreturning a time past the horizon (`inputs$horizon + 1`). Because `next_event()` is the argmin over all\nsampled times, an event scheduled past the horizon can never win — the horizon-termination event will\nalways fire first — so the transition is silently switched off. `years_till_sick1()` gates on `state == 0`\n(you can only fall sick from H); `years_till_healthy()` gates on `state == 1` (you can only recover from\nS1). The two are mirror images. As we add states in Model 6, the same trick keeps each transition wired to\nexactly the states it is legal from — no separate per-state registries, just guarded draws.\n:::\n\nNote the `reactive = TRUE` flag. The same Model 4 machinery that resamples a patient's death time when\ntheir hazard changes also resamples their recovery time the instant they enter S1: until then\n`years_till_healthy()` was returning `horizon + 1` (recovery off), and the moment `sick1()` sets `State`\nto 1 the reactive pass redraws it as a live `rexp(1, r.S1H)` (recovery on). The competing risks now race\n*both ways*.\n\n### Run it, and audit a patient who bounces\n\nA one-way cascade is hard to see in a ledger — every patient's `healthy`/`sick1` history is monotone. A\nrecurrent loop is unmistakable: a single patient visits the `healthy` counter, then `sick1`, then\n`healthy` again. We borrow the random-audit idiom from Model 4 — run the model, pick one patient, order\ntheir ledger by time — but now we deliberately select a patient who *recovered*, i.e. one with more than\none healthy spell.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(8)\nsource(here::here(\"R/model-5.R\"), chdir = TRUE)   # re-sources inputs.R + main_loop.R, redefines des_run; adds the Healthy event\narrivals <- des_run(modifyList(inputs, list(N = 200)))\n\n# A patient who recovers visits the 'healthy' counter more than once.\n# Pick one with exactly three healthy spells: enough bounces to see the loop,\n# few enough to read at a glance.\nspells <- arrivals |>\n  dplyr::filter(resource == \"healthy\") |>\n  dplyr::count(name, name = \"healthy_spells\") |>\n  dplyr::filter(healthy_spells == 3)\n\nwho <- spells$name[1]\ncat(\"Auditing:\", who, \"\\n\")\n## Auditing: patient106\n\n# Order this patient's state history by time: the H <-> S1 alternation is the recurrence.\narrivals |>\n  dplyr::filter(name == who, resource %in% c(\"healthy\", \"sick1\")) |>\n  dplyr::arrange(start_time) |>\n  dplyr::transmute(state = ifelse(resource == \"healthy\", \"H\", \"S1\"),\n                   start = round(start_time, 2),\n                   end   = round(end_time, 2),\n                   years = round(end_time - start_time, 2)) |>\n  print(row.names = FALSE)\n##  state start   end years\n##      H  0.00  7.53  7.53\n##     S1  7.53 21.57 14.04\n##      H 21.57 23.29  1.72\n##     S1 23.29 23.80  0.50\n##      H 23.80 30.00  6.20\n```\n:::\n\n\nRead the `state` column top to bottom: it **alternates** between `H` and `S1` several times — the recovery\nloop firing. This patient is healthy for the first several years, endures a long sick spell (recovery is\nslow, so S1 stays are long in this calibration), then recovers, relapses briefly, and recovers again before\nthe horizon. The contiguous `start`/`end` times confirm the costing token is being handed off cleanly at\neach transition — `release('sick1')` exactly when `seize('healthy')` happens, so no overlap and no gap, and\nthe per-state cost and QALY selectors from Model 4 will bill each spell at the right rate with no further\nchange. The loop closes; the patient genuinely moves both ways.\n\n::: {.callout-tip}\n## A quick sanity reflex\nRecurrence is also a good moment to glance at the population, not just one patient. Here recovery\n(`r.S1H = 0.05`/yr) is *slower* than onset (`r.HS1 = 0.15`/yr) — a deliberate choice for the cancer\ncontext, where pre-clinical disease rarely resolves — so patients accumulate in S1: across the cohort,\nmore person-time is spent sick than healthy (here ≈ 3,085 S1-years vs ≈ 2,120 H-years). What the audit\nconfirms is that the recovery arc nonetheless *fires* — roughly half the cohort returns to H at least once.\nThe tell-tale bug would be the opposite: *no* patient ever leaving S1, the sign of a mis-gated\n`time_to_event` (recovery left permanently disabled). That most S1 patients now progress rather than\nrecover is exactly what motivates the screening question in Part II.\n:::\n\nWith H ↔ S1 now a working two-state loop, Model 6 extends the *same* pattern one rung further down the\nladder — adding Sicker (S2) below S1 — and distils the moves we just made into a reusable checklist for\nintroducing any new state.\n\n## Model 6 — the full ladder (Sicker / S2)\n\n**Objective:** add the second disease state — *Sicker* (`S2`, numeric state `2`) — and, in doing so, discover that the model has stopped growing in kind. Everything new in Model 6 is a copy of a pattern we already have. The disease ladder is now complete (`H → S1 → S2`), and the rest of the build will reuse, not extend, the machinery assembled so far.\n\nBy now the shape of \"adding a state\" should feel familiar: Model 4 introduced `S1` and the reactive resampling that makes the engine notice a changed hazard; Model 5 added the recovery arc `S1 → H` and the state-gating idiom (`return horizon + 1` to switch a transition off). Adding `S2` asks nothing new of you. It is purely additive — five small, mechanical edits, each in a place we have touched before.\n\n::: {.callout-tip}\n## The 5-place checklist for adding a state\n\nWhenever you add a state to one of these models, you touch exactly five places. Nothing else.\n\n1. **A new event file** — the `years_till_*()` time-to-event sampler (state-gated) plus the `*()` transition that flips the `State` attribute and swaps the costing counter. Here: `event_sick2.R`.\n2. **A registry entry** — one `list(...)` in `event_registry`, `reactive = TRUE`, pointing the engine at the new sampler and transition.\n3. **A counter** — one string in the `counters` vector, so the `Inf`-capacity resource exists to tally time-in-state for costing.\n4. **A cost/QALY selector** — one `selector <- arrivals$resource == 'sick2'` block in each of `cost_arrivals()` and `qaly_arrivals()`, applying `c.S2` / `u.S2`.\n5. **A cleanup branch arm** — one more arm in `cleanup_on_termination()`'s `branch()` so a patient who dies (or hits the horizon) while in `S2` releases the right counter.\n\nIf you find yourself editing `main_loop.R` to add a state, stop: you have left the additive path.\n:::\n\nWalking the checklist for `S2`: `model-6.R` swaps in `source('event_sick2.R')` (item 1) and the matching `list(name = \"Sick2\", ...)` registry entry (item 2); the `counters` vector gains `\"sick2\"` (item 3); both valuation passes gain a `'sick2'` selector keyed to `c.S2` / `u.S2` (item 4); and the cleanup `branch()` gains its third arm, `trajectory() |> release(\"sick2\")` (item 5). The Petri-net picture is just Model 5's with one more place and one more transition arc bolted on the far end.\n\n![The full Sick-Sicker ladder. The recovery loop `H ↔ S1` from Model 5 is unchanged; we have added one place (`S2`) and the one-way progression arc `S1 → S2`. Death (not drawn) competes from every place.](../figures/petri-model6.png)\n\n### Run it\n\nSourcing `model-6.R` cleanly replaces the Model 5 definitions. The visible payoff is a *fifth* state-resource in the ledger — `sick2` — which simply was not reachable before.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(6)\nsource(here::here(\"R/model-6.R\"), chdir = TRUE)   # the full ladder: adds the Sicker (S2) state\narrivals <- des_run(modifyList(inputs, list(N = 200)))\n\n# The ledger now carries a fifth state-resource, 'sick2':\nsort(unique(arrivals$resource))\n## [1] \"death\"         \"healthy\"       \"sick1\"         \"sick2\"        \n## [5] \"time_in_model\"\n```\n:::\n\n\n### The delta: `event_sick2.R`\n\nThe new event file is a near-verbatim cousin of `event_sick1.R`. The sampler fires only out of `S1` (state `1`); the transition flips `State` to `2`, releases the `sick1` counter, and seizes `sick2`. There is no recovery arc out of `S2` in this model — once Sicker, a patient stays Sicker until death or the horizon — so there is no `S2 → S1` or `S2 → H` event to write.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# THE DELTA (event_sick2.R): identical in shape to event_sick1.R, one rung up the ladder.\n\n# State-gated sampler: a draw to S2 is only meaningful while in S1.\nyears_till_sick2 <- function(inputs)\n{\n  state <- get_attribute(env, \"State\")\n  if (state == 1)             # 1 => Sick1: progression is possible\n  {\n    rexp(1, inputs$r.S1S2)    # competing-risk draw, rate r.S1S2 per year\n  } else\n  {\n    inputs$horizon + 1        # any other state: disable this transition\n  }\n}\n\n# Transition: flip the state, swap the costing counter (sick1 -> sick2).\nsick2 <- function(traj, inputs)\n{\n  traj                      |>\n  set_attribute(\"State\", 2) |> # 2 => Sicker (S2)\n  release('sick1')          |> # stop tallying S1 time...\n  seize('sick2')               # ...start tallying S2 time\n}\n```\n:::\n\n\n### The compounding death hazard\n\nThere is one substantive change hiding in the additive work, and it lives in the death sampler, not in `event_sick2.R`. Model 6 pairs with `event_death3.R` (not the `event_death2.R` of Model 5): the only edit is a third line in the state-dependent rate.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# THE DELTA (event_death3.R): one new line for the S2 hazard ratio.\nyears_till_death <- function(inputs)\n{\n  state <- get_attribute(env, \"State\")\n  rate  <- inputs$r.HD\n  if (state == 1) rate <- rate * inputs$hr.S1D  # Model 4: S1 raises the hazard\n  if (state == 2) rate <- rate * inputs$hr.S2D  # NEW: S2 raises it much further\n  rexp(1, rate)\n}\n```\n:::\n\n\nWith `hr.S1D = 3` and `hr.S2D = 60`, the per-year death rate climbs from `r.HD = 0.005` in `H`, to `0.015` in `S1`, to `0.30` in `S2` — a sixtyfold gap between the ends of the ladder. `S2` is the deadly, advanced state: a hazard of 0.30/yr means a mean survival of only about three years once a patient reaches it. Because Death is a `reactive = TRUE` event, the engine resamples `years_till_death` the instant a patient enters `S2`, so the steeper hazard takes effect immediately rather than at the next scheduled draw. This is the engine quietly earning its keep: the hand-rolled resampling logic from Model 4 is what makes a *compounding* hazard correct here, with no extra code in the death event itself.\n\n### Audit a patient who reaches S2\n\nThe random-audit idiom from Model 4 transfers unchanged — sample one patient, order their rows by time, and read the trajectory. We filter to a patient who actually climbed to `S2` so the new rung is exercised.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Re-run under the SAME seed so the audit lands on a known patient.\nset.seed(6)\nsource(here::here(\"R/model-6.R\"), chdir = TRUE)\narrivals <- des_run(modifyList(inputs, list(N = 200)))\n\n# Pick one patient who climbed all the way to S2, then read their history in order.\nset.seed(11)\nwho <- arrivals |>\n  dplyr::filter(resource == \"sick2\") |>\n  dplyr::distinct(name) |>\n  dplyr::slice_sample(n = 1) |>\n  dplyr::pull(name)\n\narrivals |>\n  dplyr::filter(name == who, resource != \"time_in_model\") |>\n  dplyr::arrange(start_time) |>\n  dplyr::transmute(resource,\n                   start_time = round(start_time, 1),\n                   end_time   = round(end_time, 1),\n                   cost       = round(cost)) |>\n  knitr::kable(caption = paste(\"State history for\", who))\n```\n\n::: {.cell-output-display}\n\n\nTable: State history for patient113\n\n|resource | start_time| end_time| cost|\n|:--------|----------:|--------:|----:|\n|healthy  |        0.0|      1.6|    0|\n|sick1    |        1.6|      6.2| 1373|\n|sick2    |        6.2|      8.9| 2718|\n|death    |        8.9|      8.9|    0|\n\n\n:::\n:::\n\n\nRead top to bottom, this is the whole curriculum so far in one patient: `H → S1 → S2 → death`. The patient is healthy briefly, spends a few years in S1, then progresses to `S2` — and, with no recovery arc out of S2 and a sixtyfold death hazard, dies within a few years of reaching it, long before the 30-year horizon. The `sick2` row (billed at `c.S2 = 1000`/year) is short but it is where the lost life-years concentrate: advanced disease here is cheap to *manage* but expensive in *health*. It is exactly this cohort — the patients who progress to deadly S2 because they were never treated early — that the screening question in Part II is about reaching in time.\n\n::: {.callout-note}\n## Why this is the last \"add a state\" section\nModels 4–6 were three turns of one crank: state attribute, reactive resampling, state-gated samplers, per-state costing, cleanup arm. The ladder `H → S1 → S2` is now complete and validated patient-by-patient. From here the build changes character — Model 7 adds a *comparator* (and the first ICER), and Part II replaces an `Inf`-capacity counter with a genuinely finite one. No new disease states are coming; the machinery is done.\n:::\n\n# Part II — A screening decision\n\nPart I built a faithful natural history: a cohort flows `H → S1 → S2`, recovers\noccasionally, and dies — and we can price the result in discounted costs and QALYs.\nNothing in it was contended; `simmer` was only a timeout-and-tally engine. We now put\nthat model to work on a concrete policy question, and in doing so introduce the one\ningredient Part I lacked: a resource that more than one patient wants at once.\n\n::: {.callout-note}\n## The decision (the Republic of SMDM)\nA lower-middle-income country screens for a cancer with a long pre-clinical phase\n(our `S1`). The **standard of care** is an accurate **molecular test** — high\nsensitivity and specificity — but it needs cold chain, imported cartridges, and a\nlaboratory, so it is expensive and reaches only about **12 %** of eligible people.\nA challenger has appeared: a cheap **field test** a primary-care nurse can run, at\nroughly one-twelfth the cost, which could reach **50 %** — but it is less accurate\n(more missed cancers, *many* more false alarms). Every screen-positive, true or\nfalse, must be **confirmed** by a diagnostic workup before treatment, and that\nconfirmatory capacity is **fixed**. The question the rest of this document answers:\n*does the field test's flood of referrals overwhelm the bottleneck, and does that\nchange the recommendation?*\n:::\n\nWe reach the answer in four steps. Model 7 turns disease into a *decision* by adding a\nscreening program and establishing the molecular test as the standard of care. Model 8\nintroduces the field test as a comparator and — ignoring capacity — finds it dominant.\nModel 9 inserts a fixed confirmatory wait and shows it changes little. Only in Part III,\nwhen the bottleneck becomes genuinely finite and the wait becomes *endogenous*, does the\npicture move.\n\n## Model 7 — the intervention: a screening program\n\n**Objective:** turn the natural-history model into a *comparative* one. Cost-effectiveness\nanalysis needs two worlds — with the intervention and without — run under the same rules,\nso the difference between them is the intervention's effect and nothing else. Our\nintervention is **screening**: a one-time test that can catch a patient in the\npre-clinical `S1` window, where treatment still works, before they progress to deadly `S2`.\n\nThree ideas carry the section, each a small extension of machinery you already have.\n\n**First, a strategy is just a flag.** The `inputs$strategy` value (`'noscreen'`, `'mol'`,\nor `'field'`) is read once, per patient, and every event handler can branch on it. To run\na different arm we change one value in the inputs list — nothing in the engine moves.\n\n**Second, screening is a one-time event, staggered over a rollout.** A real program does\nnot reach everyone on the same day; it rolls out over years. So each patient draws their\nown screen time, `~Uniform(t.screen.start, t.screen.end)`, at birth, and a single\nnon-reactive `Screen` event fires at that time. When it fires, two independent draws\ndecide what happens: one for **coverage** (is this person reached by the program at all?),\none for the **result** (given a test, is it positive?). Separating coverage from result is\nwhat lets us cost the program honestly — *everyone screened pays for the test*, not only\nthose who turn out positive.\n\n**Third, a detected true positive is treated, and treatment is an effect plus three costs.**\nA patient still in `S1` whose test is positive is confirmed and treated: they move from the\n`sick1` tally to a `treated_s1` tally (so we can value treated time differently), and an\nattribute `TreatA = 1` switches their `S1 → S2` progression onto the treated hazard\n(`hr.TrtS1S2 = 0.20` — an 80 % reduction). The money enters as three one-time charges,\nstored as attributes and folded into the patient's total: the **test** (`c.screen`), the\n**confirmatory workup** (`c.confirm`), and the **treatment** itself (`c.Trt.onetime`, a\nsingle procedure, not an annual drip).\n\n![The Petri net for Model 7. A one-time `Screen` transition can move an `S1` token onto treatment (`treated_s1`), where the `S1 → S2` progression arc fires at a reduced rate. Healthy people who screen positive are *false positives*: they pay for the test and workup but are not treated. Everything from Part I still fires underneath.](../figures/petri-model6.png){width=92%}\n\n### The delta: `event_screen.R`\n\nThe whole intervention is one event file. Its `time_to_event` returns the patient's\npre-drawn screen time once, then disables itself (the Part I state-gating idiom). Its\nhandler is a `branch()` over four outcomes — not screened, true positive, false positive,\nscreened-negative — and the costs attach in exactly the branches that incur them.\n\n```r\n# THE DELTA (event_screen.R): coverage and result are SEPARATE draws.\nscreen <- function(traj, inputs) {\n  traj |>\n  set_attribute(\"Screened\", 1) |>          # fire once, then this event is past the horizon\n  branch(\n    function() {\n      state <- get_attribute(env, \"State\")\n      cov  <- if (inputs$strategy == 'mol') inputs$cov.mol  else inputs$cov.field\n      sens <- if (inputs$strategy == 'mol') inputs$sens.mol else inputs$sens.field\n      spec <- if (inputs$strategy == 'mol') inputs$spec.mol else inputs$spec.field\n      u_cov <- draw_unif(\"screen\")          # reached by the program?\n      u_res <- draw_unif(\"screen\")          # test result?\n      if (inputs$strategy == 'noscreen') return(1L)   # no program\n      if (state >= 2)        return(1L)               # symptomatic: outside screening\n      if (u_cov >= cov)      return(1L)               # not reached -> no test, no cost\n      if (state == 1L && u_res < sens)       return(2L)   # TRUE positive\n      if (state == 0L && u_res < (1 - spec)) return(3L)   # FALSE positive\n      return(4L)                                          # screened negative\n    },\n    continue = rep(TRUE, 4),\n    trajectory(),                                         # 1: not screened — no cost\n    trajectory() |>                                       # 2: TP -> confirm + treat\n      set_attribute(\"ScreenCost\",  screen_unit_cost) |>\n      set_attribute(\"ConfirmCost\", \\() inputs$c.confirm) |>\n      set_attribute(\"TreatA\", 1) |>\n      set_attribute(\"TreatCost\", \\() inputs$c.Trt.onetime) |>\n      release(\"sick1\") |> seize(\"treated_s1\"),\n    trajectory() |>                                       # 3: FP -> confirm cost, no treatment\n      set_attribute(\"ScreenCost\",  screen_unit_cost) |>\n      set_attribute(\"ConfirmCost\", \\() inputs$c.confirm),\n    trajectory() |>                                       # 4: screened negative -> test cost only\n      set_attribute(\"ScreenCost\",  screen_unit_cost)\n  )\n}\n```\n\n::: {.callout-note}\n## Why coverage and result are separate draws\nIt is tempting to fold coverage into the positive rate — detect a true positive with\nprobability `cov × sens` in one `runif()`. That gets the *detection* count right but the\n*cost* wrong: it never lets you charge the test to the people who were screened and came\nback negative, who are the overwhelming majority and the bulk of a program's spend. The\nfield test's entire value proposition is \"a cheap test at scale,\" and you cannot see it\nunless the scale — every negative screen — is on the books. So coverage gates first (and\nbills the test), then the result decides what happens next. The `draw_unif()` helper is\nour common-random-number draw; for now read it as `runif(1)` — Model 8 explains what it\nreally does.\n:::\n\n### Run it: molecular screening vs no screening\n\nSourcing `model-7.R` redefines `des_run()` once more. We run the no-screen world and the\nmolecular-screening world under matched seeds and difference them.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsource(here::here(\"R/model-7.R\"), chdir = TRUE)   # adds the Screen event, treated_s1, and the screening costs\n## No screen : dcost =     2943  dQALY = 11.502\n## Molecular : dcost =     3075  dQALY = 11.656\n## ICER (mol vs no-screen) = 858 per QALY\n\n# Run one arm: aggregate the ledger to per-patient discounted totals, average over patients.\n# des_run() takes a seed and pairs the two arms (common random numbers; see Model 8).\nrun_arm <- function(strategy, N = 2000, seed = 7) {\n  des_run(modifyList(inputs, list(strategy = strategy, N = N)), seed = seed) |>\n    group_by(name) |>\n    summarise(cost = sum(dcost), qaly = sum(dqaly), .groups = \"drop\") |>\n    summarise(cost = mean(cost), qaly = mean(qaly))\n}\n\nnoscreen <- run_arm(\"noscreen\")\nmol      <- run_arm(\"mol\")\n\ndcost <- mol$cost - noscreen$cost\ndqaly <- mol$qaly - noscreen$qaly\nicer  <- dcost / dqaly\n\nknitr::kable(\n  data.frame(\n    Strategy = c(\"No screening\", \"Molecular (SoC)\", \"Incremental\"),\n    Cost     = round(c(noscreen$cost, mol$cost, dcost)),\n    QALYs    = round(c(noscreen$qaly, mol$qaly, dqaly), 3)),\n  align = \"lrr\", format.args = list(big.mark = \",\"),\n  caption = \"Molecular screening vs no screening (N = 2000, discounted, paired seeds).\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Molecular screening vs no screening (N = 2000, discounted, paired seeds).\n\n|Strategy        |  Cost|  QALYs|\n|:---------------|-----:|------:|\n|No screening    | 2,917| 11.369|\n|Molecular (SoC) | 3,034| 11.505|\n|Incremental     |   117|  0.136|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n## ICER (molecular vs no screening) = 860 per QALY  (WTP = 1e+05)\n```\n:::\n\n\nMolecular screening costs a little more and buys meaningfully more health: catching some\npatients in `S1` and cutting their progression to deadly `S2` is worth far more in QALYs\nthan it costs. The ICER lands around **\\$860 per QALY** — an order of magnitude below the\n\\$100,000 willingness-to-pay threshold in `inputs$wtp`. So molecular screening is clearly\ncost-effective, and from here it is our **standard of care**: the world we compare the\ncheaper field test *against*. That comparison is Model 8 — and it is where the trouble\nstarts.\n\n\n## Model 8 — the comparator: the field test\n\n**Objective:** swap the comparator. Model 7 weighed molecular screening against doing\nnothing; the actual decision weighs the cheap **field test** against the molecular\n**standard of care**. Structurally this asks *nothing* new of the model. The field test\nis the same `screen` event with different numbers in `inputs`: lower coverage cost,\nhigher coverage, lower sensitivity and specificity. We change a handful of parameters and\nre-run.\n\n```r\n# THE DELTA (inputs): the field test is the molecular test with different dials.\ncov.mol  = 0.12; sens.mol  = 0.95; spec.mol  = 0.95; c.screen.mol   = 1200   # standard of care\ncov.field= 0.50; sens.field= 0.70; spec.field= 0.70; c.screen.field =  100   # the challenger\n```\n\nFour forces now pull against each other, and the model's job is to net them out. The field\ntest (1) reaches **four times** as many people but (2) **misses more** of the cancers it\nshould catch (lower sensitivity) and (3) raises **far more false alarms** (lower\nspecificity), while (4) costing a twelfth as much per test. Whether it is a good idea is\nnot something you can read off any single number; it is the population-level integral of\nall four, which is exactly what the simulation computes.\n\n### The result, ignoring capacity: the field test dominates\n\nWe run both arms and difference them, paired on the same patients.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsource(here::here(\"R/model-8.R\"), chdir = TRUE)   # same screen event; mol vs field is a parameter change\n## Molecular : dcost =     3075  dQALY = 11.656\n## Field     : dcost =     3043  dQALY = 11.905\n## Δcost = -32  ΔdQALY = 0.249\n## SE quadrant: field test is dominant (lower cost, more QALYs)\n\nrun_arm <- function(strategy, N = 2000, seed = 7) {\n  des_run(modifyList(inputs, list(strategy = strategy, N = N)), seed = seed) |>\n    group_by(name) |>\n    summarise(cost = sum(dcost), qaly = sum(dqaly), .groups = \"drop\") |>\n    summarise(cost = mean(cost), qaly = mean(qaly))\n}\n\nmol   <- run_arm(\"mol\")\nfield <- run_arm(\"field\")\ndcost <- field$cost - mol$cost\ndqaly <- field$qaly - mol$qaly\n\nknitr::kable(\n  data.frame(\n    Strategy = c(\"Molecular (SoC)\", \"Field test\", \"Incremental (field − mol)\"),\n    Cost     = round(c(mol$cost, field$cost, dcost)),\n    QALYs    = round(c(mol$qaly, field$qaly, dqaly), 3)),\n  align = \"lrr\", format.args = list(big.mark = \",\"),\n  caption = \"Field test vs molecular standard of care, no capacity constraint (N = 2000, paired seeds).\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Field test vs molecular standard of care, no capacity constraint (N = 2000, paired seeds).\n\n|Strategy                  |  Cost|  QALYs|\n|:-------------------------|-----:|------:|\n|Molecular (SoC)           | 3,034| 11.505|\n|Field test                | 3,005| 11.766|\n|Incremental (field − mol) |   -29|  0.261|\n\n\n:::\n:::\n\n\nThe incremental row is in the **southeast quadrant**: the field test is **cheaper *and*\nmore effective** — it *dominates* the standard of care. The arithmetic is intuitive once\nyou see which force wins. Reaching 50 % of people with a 70 %-sensitive test finds more\ntrue cancers in absolute terms than reaching 12 % with a 95 %-sensitive one\n(`0.50 × 0.70` against `0.12 × 0.95`), so more patients are caught in `S1` and steered off\nthe road to deadly `S2` — that is the QALY gain. And because the test itself is so much\ncheaper at scale, the program costs *less* even after paying for the extra false-positive\nworkups — that is the cost saving. On paper, the field test is an easy yes.\n\n::: {.callout-warning}\nThis conclusion has a load-bearing assumption buried in it: that *every* screen-positive\nis confirmed and treated **on demand**. The field test's whole problem is that it generates\nthree to four times the referrals — and the confirmatory bottleneck downstream cannot\nabsorb them. We have not modelled that yet. Models 9 onward do, and the easy yes does not\nsurvive it.\n:::\n\n## Common random numbers: making the difference visible\n\nBefore we go on, a word on *how* we read a difference this small. The incremental QALY\nabove is around a quarter of a QALY per person — but the QALYs themselves are ~11.5, and\nthey vary a lot from cohort to cohort because lifespan is stochastic. If we ran the two\narms on **independent** random draws, that cohort-to-cohort noise would swamp the signal:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Re-run the field-minus-molecular QALY difference across several independent cohorts,\n# once with common random numbers (paired patients) and once without.\ndelta_q <- function(seed, crn_off = FALSE) {\n  CRN$force_disabled <- crn_off                    # toggle the per-patient banks\n  d <- run_arm(\"field\", N = 1000, seed = seed)$qaly - run_arm(\"mol\", N = 1000, seed = seed)$qaly\n  CRN$force_disabled <- FALSE\n  d\n}\nseeds <- c(1, 2, 3, 4, 5, 6, 7, 8) * 123457L       # widely spaced -> genuinely independent cohorts\nwith_crn    <- sapply(seeds, delta_q, crn_off = FALSE)\nwithout_crn <- sapply(seeds, delta_q, crn_off = TRUE)\ndata.frame(\n  Estimator = c(\"With CRN (paired)\", \"Without CRN (independent)\"),\n  `Mean ΔQALY` = round(c(mean(with_crn), mean(without_crn)), 3),\n  `SD across cohorts` = round(c(sd(with_crn), sd(without_crn)), 3),\n  check.names = FALSE) |>\n  knitr::kable(caption = \"The same difference, estimated 8 times. CRN roughly thirds the cohort noise.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: The same difference, estimated 8 times. CRN roughly thirds the cohort noise.\n\n|Estimator                 | Mean ΔQALY| SD across cohorts|\n|:-------------------------|----------:|-----------------:|\n|With CRN (paired)         |      0.254|             0.050|\n|Without CRN (independent) |      0.316|             0.152|\n\n\n:::\n:::\n\n\nWithout common random numbers the estimate wobbles by ~0.15 QALY from cohort to cohort —\n*larger than the signal itself*, so a single unlucky run could report no benefit, or the\nwrong sign. With CRN it wobbles by ~0.05. The trick is to give the two strategy arms the\n**same patients**: the same birth ages, the same disease-event times, the same\nscreen-coverage and test-result draws — so the only thing that differs between the arms is\nthe *decision*, and the difference is the decision's effect rather than luck.\n\n::: {.callout-note}\n## How the banks work (`R/crn.R`)\n`simmer` shares one global random stream across all arrivals, so the naive fix — `set.seed()`\nbefore each arm — desynchronises the moment one arm takes a branch the other does not.\nInstead, each patient draws from a **private bank** of uniforms, seeded deterministically\nfrom their own index, and every stochastic step consumes that bank by **inverse-CDF**:\n`qexp(u, rate)` in place of `rexp(1, rate)`, `u < p` in place of `runif(1) < p`. Because a\npatient's bank is fixed and private, the molecular and field arms hand patient *i* the\nexact same draws — patient *i*'s disease unfolds identically until the screening *decision*\ndiverges. The shared helpers `draw_exp()` / `draw_unif()` fall back to plain `rexp`/`runif`\nwhen no bank is armed, so Models 1–6 are bit-for-bit unchanged; the screening models arm a\nbank per patient. (This adapts the per-event CRN streams of the RIPS-CVD microsimulation to\n`simmer`'s next-event engine. CRN aligns the two *strategies* within a model; it cannot\nalign two different *models* — a fact that matters in Part IV.)\n:::\n\n## Model 9 — an exogenous queue, and why it reassures falsely\n\n**Objective:** take the first, tempting step toward modelling the bottleneck — and watch\nit fail to capture the problem. We know confirmation is not instantaneous, so the obvious\nfix is to put a **wait** between a positive screen and treatment. The simplest wait is an\n**exogenous** one: a fixed delay drawn from a distribution we read off the current system —\nhere a lognormal with a mean of about **18 weeks**, the wait observed under the\n(uncongested) molecular program today. During that wait the patient's disease keeps\nprogressing; a true positive who slips from `S1` to `S2` before their confirmation arrives\nhas missed the treatment window.\n\n```r\n# THE DELTA (model-9): a positive screen schedules a deferred 'Confirm' event.\n#   The wait is drawn from a FIXED distribution -- it does not know how many other\n#   patients are waiting. Disease keeps racing during the delay (death/progress/recover).\nset_attribute(\"tConfirm\", function()\n  now(env) + qlnorm(draw_unif(\"confirm\"), inputs$confirm_wait_logmean, inputs$confirm_wait_logsd))\n```\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsource(here::here(\"R/model-9.R\"), chdir = TRUE)   # adds a deferred, fixed-distribution confirmation wait\n## Molecular (exog queue): dcost =     3063  dQALY = 11.621\n## Field     (exog queue): dcost =     3040  dQALY = 11.910\n## Δcost = -23  ΔdQALY = 0.289\n## Quadrant: SE (dominant)\nmol   <- run_arm(\"mol\")\nfield <- run_arm(\"field\")\nknitr::kable(\n  data.frame(\n    Strategy = c(\"Molecular (SoC)\", \"Field test\", \"Incremental (field − mol)\"),\n    Cost     = round(c(mol$cost, field$cost, field$cost - mol$cost)),\n    QALYs    = round(c(mol$qaly, field$qaly, field$qaly - mol$qaly), 3)),\n  align = \"lrr\", format.args = list(big.mark = \",\"),\n  caption = \"Field vs molecular with an EXOGENOUS 18-week confirmation wait (N = 2000, paired seeds).\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Field vs molecular with an EXOGENOUS 18-week confirmation wait (N = 2000, paired seeds).\n\n|Strategy                  |  Cost|  QALYs|\n|:-------------------------|-----:|------:|\n|Molecular (SoC)           | 3,023| 11.469|\n|Field test                | 2,999| 11.736|\n|Incremental (field − mol) |   -24|  0.267|\n\n\n:::\n:::\n\n\nThe verdict barely moves: the field test is still firmly in the southeast quadrant,\ncheaper and more effective. This is **false reassurance**, and the reason is structural,\nnot numerical. An exogenous wait is the *same fixed distribution for both arms* — it does\nnot know that the field test sends three to four times as many people into the queue. It\ncharges the molecular-era wait to a program that would, in reality, generate a far longer\none. A delay that does not respond to load cannot capture a bottleneck, because a\nbottleneck *is* the response to load. To see the problem we have to let the wait be set by\nthe queue itself — to make it **endogenous**. That is the finite resource Part I kept\npromising, and it is where DES finally earns its keep.\n\n\n# Part III — Two designs for the endogenous queue\n\nModel 9 failed for a precise reason: its wait was *exogenous*, the same fixed\ndistribution regardless of how many patients were in line. A real bottleneck is the\nopposite — *my* wait is a function of *everyone else's* demand, right now. To capture it\nwe make the confirmatory step a **genuinely finite resource**: `n` confirmation slots\n(here ≈ 2 per 1,000 eligible people), each holding a patient for the length of a workup.\nWhen the field test floods it with referrals, the slots fill, a queue forms, and patients\nwait — while their disease keeps progressing.\n\nThis is the moment Part I kept deferring, and it comes with a hard constraint. The\nhand-rolled engine resolves competing risks by sampling each event's time and taking the\n`argmin`. If we let a patient **block** in a `simmer` `seize()` — the obvious way to model\na queue — the arrival stops dead in the queue, and with it the patient's whole event clock:\nthey cannot die, progress, or recover while they wait. The two paradigms do not compose.\nSo every correct design must honour one **invariant**:\n\n> The patient never blocks. Disease keeps racing during the wait. The capacity cap is\n> enforced exactly. No slot is leaked or double-released.\n\nWe give two designs that honour it. **Approach A** computes the wait analytically from live\noccupancy and never touches the engine. **Approach B** spawns a disposable companion that\nholds the *real* blocking queue on the patient's behalf. They are the convenient design and\nthe faithful one, and Part IV shows where they agree and where they part.\n\n## Approach A — the endogenous-wait registry event (Model 10)\n\nThe cleanest idea first: leave the patient in the event loop and add **one more registry\nevent** — \"get confirmed\" — whose `time_to_event` *reads the live queue* and returns how\nlong this patient should expect to wait. Because registry events are reactive, the engine\nre-samples it after every transition, so the estimate always reflects current congestion.\nA real `add_resource(\"confirm\", capacity = c)` holds the cap (it is **not** an `Inf`\ncounter); a global FIFO waitlist records who is in line.\n\n### The endogenous wait: reading live occupancy\n\n```r\n# THE DELTA (model10) — years_till_confirm(): the ENDOGENOUS wait.\n# Reactive => re-sampled after every event, so congestion is always current.\nyears_till_confirm <- function(inputs) {\n  if (get_attribute(env, \"WaitingConfirm\") != 1) return(inputs$horizon + 1)  # not in line\n  cap  <- get_capacity(env, \"confirm\")\n  busy <- get_server_count(env, \"confirm\")        # slots occupied right now\n  pos  <- wl_position(get_name(env))              # my place in the FIFO line\n  if (cap - busy >= pos) {\n    draw_exp(\"confirm\", inputs$rate_admit_free)   # a slot is (in expectation) free for me -> ~now\n  } else {\n    n_ahead <- pos - (cap - busy)\n    draw_exp(\"confirm\", cap * inputs$mu.confirm / n_ahead)  # M/M/c-flavoured wait\n  }\n}\n```\n\n### The fire-time guard: enforcing the cap exactly\n\nThe analytic wait says *when* a slot should free; it cannot guarantee one actually has. So\nwhen the event fires we **guard** it: seize `confirm` only if a slot is genuinely free, and\notherwise do nothing — the reactive reschedule will try again. The cap is therefore\nenforced *exactly* by `simmer`'s own server count, while the patient never blocks.\n\n```r\n# THE DELTA (model10) — get_confirm(): the FIRE-TIME GUARD.\nget_confirm <- function(traj, inputs) {\n  traj |> branch(\n    function() if (get_capacity(env, \"confirm\") > get_server_count(env, \"confirm\")) 1L else 2L,\n    continue = c(TRUE, TRUE),\n    trajectory() |>                          # a slot is free: take it, leave the line, treat if still S1\n      seize(\"confirm\") |> set_attribute(\"HasConfirm\", 1) |>\n      ( \\(t) confirm_and_maybe_treat(t) )(),\n    trajectory()                             # no slot free: skip; the reactive reschedule re-defers\n  )\n}\n```\n\nThe selling point of A is restraint: it adds contention **without editing `main_loop.R`**,\nthe decade-stable engine. Everything is one resource, one waitlist, and two registry\nevents (acquire, release). Run it against the molecular standard of care:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsource(here::here(\"R/model10.R\"), chdir = TRUE)   # Approach A: finite confirm resource + endogenous wait\n## Molecular (endog queue, A): dcost =     3079  dQALY = 11.565\n## Field     (endog queue, A): dcost =     2989  dQALY = 11.598\n## Δcost = -91  ΔdQALY = 0.032\n## Quadrant: SE (dominant)\nrun_arm <- function(strategy, N = 2000, seed = 7) {\n  des_run(modifyList(inputs, list(strategy = strategy, N = N)), seed = seed) |>\n    group_by(name) |>\n    summarise(cost = sum(dcost), qaly = sum(dqaly), .groups = \"drop\") |>\n    summarise(cost = mean(cost), qaly = mean(qaly))\n}\nmol <- run_arm(\"mol\"); field <- run_arm(\"field\")\nknitr::kable(\n  data.frame(\n    Strategy = c(\"Molecular (SoC)\", \"Field test\", \"Incremental (field − mol)\"),\n    Cost     = round(c(mol$cost, field$cost, field$cost - mol$cost)),\n    QALYs    = round(c(mol$qaly, field$qaly, field$qaly - mol$qaly), 3)),\n  align = \"lrr\", format.args = list(big.mark = \",\"),\n  caption = \"Approach A — endogenous confirmatory queue (N = 2000, paired seeds).\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Approach A — endogenous confirmatory queue (N = 2000, paired seeds).\n\n|Strategy                  |  Cost|  QALYs|\n|:-------------------------|-----:|------:|\n|Molecular (SoC)           | 3,030| 11.450|\n|Field test                | 2,978| 11.434|\n|Incremental (field − mol) |   -52| -0.016|\n\n\n:::\n:::\n\n\nThe field test is **still cheaper** — its cost advantage was always the test, not the\nqueue — but its QALY advantage has **evaporated**: the incremental effect that was +0.26\nwith no queue, and +0.27 with the exogenous one, is now essentially **zero, even slightly\nnegative**. The bottleneck did exactly what the exogenous wait could not show: the field\ntest's referral flood backs up the queue, true positives progress to `S2` before their\nconfirmation arrives, and the extra cancers it caught at screening are lost again in the\nline. The ICER has drifted out of the southeast (dominant) quadrant and onto the boundary\nof the **southwest** — cheaper, but no longer clearly better.\n\n::: {.callout-note}\n## Honest caveat: the cap is exact, the wait *distribution* is an approximation\nApproach A enforces the capacity cap to the patient (the guard never over-fills), but the\n*wait itself* is a single-exponential, M/M/c-flavoured estimate — correct in its first\nmoment under saturation, not an exact emergent queue. For mean CEA endpoints that is\nusually enough; when the **shape** of the wait matters, you want Approach B. Note also that\nA's queue is invisible to `simmer`'s resource monitor (`get_mon_resources()` shows zero\nqueue), because the patient never actually blocks on the resource — the line lives in the\nexternal waitlist, not in the server.\n:::\n\n## Approach B — the claim-ticket companion (Model 11)\n\nApproach B refuses the approximation and pays for it in machinery. The idea: the patient\nstays in the event loop, never blocking — but at the moment they screen positive they\n**`clone()` a disposable companion** whose only job is to stand in the *real* `seize()`\nqueue. The companion carries no disease clock, so it is free to block; when it reaches the\nfront and acquires a slot, it **signals** the patient, who then (still in the loop) starts\ntreatment. The queue is `simmer`'s own FIFO — exact, not modelled.\n\nTwo details make it correct. First, the signal must name the *patient*, not the companion —\nso we key it on an inherited `pid` attribute (inside the companion, `get_name(env)` would\nreturn the *companion's* name). Second, the patient does not treat inside the signal\nhandler; the handler sets a flag and forces a **registry event** to fire, so the reactive\nresample re-draws progression at the *treated* rate. (Treating inside the handler alone\nwould not resample the competing risks.)\n\n```r\n# THE DELTA (model11) — spawn the companion, then trap its acquire signal.\nspawn_confirm_companion <- function(traj, inputs, is_tp) {\n  traj |>\n    set_attribute(\"IsTruePos\", is_tp) |>\n    trap(sig_acq,                                   # listen for \"your slot is ready\" (keyed on pid)\n         handler = trajectory() |>\n           set_attribute(\"confirmReady\", 1) |>\n           set_attribute(\"aConfirmAcq\", function() now(env))) |>   # force the registry event to fire now\n    clone(n = 2,\n          trajectory(\"self\"),                       # the patient: re-enters the event loop, never blocks\n          companion_trajectory(inputs)) |>          # the companion: stands in the real queue\n    synchronize(wait = FALSE)                        # the self-clone survives instantly\n}\n\n# The companion holds the real blocking queue; carries NO disease tally -> nothing to freeze.\ncompanion_trajectory <- function(inputs) {\n  trajectory(\"companion\") |>\n    renege_if(sig_abandon, out = trajectory()) |>   # patient left S1 while queued -> drop out\n    seize(\"confirm\", 1) |>                           # BLOCKS here until a slot frees (this is the real FIFO)\n    renege_abort() |>\n    send(sig_acq) |>                                 # tell the patient: slot acquired\n    timeout(function() rexp(1, inputs$mu.confirm)) |># hold the slot for the workup\n    release(\"confirm\", 1)\n}\n```\n\nRun it the same way:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsource(here::here(\"R/model11.R\"), chdir = TRUE)   # Approach B: claim-ticket companion holds the exact FIFO queue\n## Molecular (FIFO companion, B): dcost =     3060  dQALY = 11.601\n## Field     (FIFO companion, B): dcost =     3005  dQALY = 11.565\n## Δcost = -55  ΔdQALY = -0.037\n## Quadrant: SW\nmol <- run_arm(\"mol\"); field <- run_arm(\"field\")\nknitr::kable(\n  data.frame(\n    Strategy = c(\"Molecular (SoC)\", \"Field test\", \"Incremental (field − mol)\"),\n    Cost     = round(c(mol$cost, field$cost, field$cost - mol$cost)),\n    QALYs    = round(c(mol$qaly, field$qaly, field$qaly - mol$qaly), 3)),\n  align = \"lrr\", format.args = list(big.mark = \",\"),\n  caption = \"Approach B — exact FIFO confirmatory queue (N = 2000, paired seeds).\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Approach B — exact FIFO confirmatory queue (N = 2000, paired seeds).\n\n|Strategy                  |  Cost|  QALYs|\n|:-------------------------|-----:|------:|\n|Molecular (SoC)           | 3,018| 11.466|\n|Field test                | 2,970| 11.446|\n|Incremental (field − mol) |   -48| -0.020|\n\n\n:::\n:::\n\n\nApproach B tells the same story — field cheaper, its effectiveness advantage gone, the ICER\nin the **southwest** — but it gets there through the *exact* queue rather than an analytic\nproxy. Unlike A, B's queue is real and visible: `get_mon_resources()` shows it peaking at a\ncouple of hundred patients waiting behind the field test's referral flood. That fidelity is\nB's selling point.\n\n::: {.callout-warning}\n## B's fragility — each invariant breaks silently if violated\nB works only because several fragile things are exactly right: the signal is keyed on the\ninherited `pid` (key it on `get_name(env)` and the companion signals nobody); the patient\ntreats via a *registry event*, not in the trap handler (otherwise the competing risks are\nnot resampled); the companion carries **no** state tally (otherwise the clone double-counts\nor double-releases it); and leaving `S1` must `send()` an abandon signal so a still-queued\ncompanion reneges out. Get any one wrong and the model produces plausible-looking but wrong\nnumbers. Approach A has none of these failure modes — which is the whole tradeoff, and the\nsubject of Part IV.\n:::\n\n\n# Part IV — The swing, and which model to trust\n\nWe now have four readings of the same decision, differing only in how seriously they take\nthe confirmatory bottleneck. Lined up, they tell the story the whole document was built to\ntell.\n\n## The cost-effectiveness drift: SE → SW\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Re-run the field-minus-molecular increment under each treatment of the queue.\nincr <- function(model_file, N = 2000, seed = 7) {\n  source(here::here(\"R\", model_file), chdir = TRUE)   # each redefines des_run() cleanly\n  arm <- function(s) des_run(modifyList(inputs, list(strategy = s, N = N)), seed = seed) |>\n    group_by(name) |> summarise(c = sum(dcost), q = sum(dqaly), .groups = \"drop\") |>\n    summarise(c = mean(c), q = mean(q))\n  m <- arm(\"mol\"); f <- arm(\"field\")\n  c(dcost = f$c - m$c, dqaly = f$q - m$q)\n}\ndrift <- rbind(\n  `8  — no queue`           = incr(\"model-8.R\"),\n  `9  — exogenous wait`     = incr(\"model-9.R\"),\n  `10 — endogenous (A)`     = incr(\"model10.R\"),\n  `11 — endogenous (B)`     = incr(\"model11.R\"))\n## Molecular : dcost =     3075  dQALY = 11.656\n## Field     : dcost =     3043  dQALY = 11.905\n## Δcost = -32  ΔdQALY = 0.249\n## SE quadrant: field test is dominant (lower cost, more QALYs)\n## Molecular (exog queue): dcost =     3063  dQALY = 11.621\n## Field     (exog queue): dcost =     3040  dQALY = 11.910\n## Δcost = -23  ΔdQALY = 0.289\n## Quadrant: SE (dominant)\n## Molecular (endog queue, A): dcost =     3079  dQALY = 11.565\n## Field     (endog queue, A): dcost =     2989  dQALY = 11.598\n## Δcost = -91  ΔdQALY = 0.032\n## Quadrant: SE (dominant)\n## Molecular (FIFO companion, B): dcost =     3060  dQALY = 11.601\n## Field     (FIFO companion, B): dcost =     3005  dQALY = 11.565\n## Δcost = -55  ΔdQALY = -0.037\n## Quadrant: SW\nquad <- ifelse(drift[,\"dcost\"] < 0 & drift[,\"dqaly\"] > 0, \"SE (dominant)\",\n        ifelse(drift[,\"dcost\"] < 0 & drift[,\"dqaly\"] < 0, \"SW (cheaper, worse)\", \"other\"))\nknitr::kable(\n  data.frame(`Δ cost` = round(drift[,\"dcost\"]), `Δ QALY` = round(drift[,\"dqaly\"], 3),\n             Quadrant = quad, check.names = FALSE),\n  caption = \"The same field-vs-molecular decision, under four treatments of the confirmatory queue.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: The same field-vs-molecular decision, under four treatments of the confirmatory queue.\n\n|                    | Δ cost| Δ QALY|Quadrant            |\n|:-------------------|------:|------:|:-------------------|\n|8  — no queue       |    -29|  0.261|SE (dominant)       |\n|9  — exogenous wait |    -24|  0.267|SE (dominant)       |\n|10 — endogenous (A) |    -52| -0.016|SW (cheaper, worse) |\n|11 — endogenous (B) |    -48| -0.020|SW (cheaper, worse) |\n\n\n:::\n:::\n\n\nRead the `Δ QALY` column top to bottom: **+0.26 → +0.27 → −0.02 → −0.02**. The cost column\nnever changes sign — the field test is cheaper in every row, because its cost advantage is\nthe *test*, and the queue does not touch that. What the queue moves is the **health** axis,\nand it moves it across zero. Ignoring capacity, or modelling it exogenously, the field test\nis **dominant** (southeast): an easy yes. Model the bottleneck *endogenously* — by either\ndesign — and the same field test lands in the **southwest**: still cheaper, but now *worse*\nfor health, because the referrals it generates overwhelm the confirmatory capacity and its\nextra cancers progress untreated in the line. The recommendation does not merely weaken; it\n**flips quadrant**. A decision-maker who saw only Models 8–9 would adopt the field test as a\nfree win. A decision-maker who saw Models 10–11 faces a genuine trade-off: real savings\nbought with real health loss — the \"southwest-quadrant quandary.\"\n\n## Approach A vs B: where they agree, and where they part\n\nThe two endogenous designs agreed in the table above. Do they agree in general? We compared\nthem by **replication** — not by shared seeds. (Common random numbers align the two\n*strategies* within one model, but they cannot align two *different* models: A and B inject\ndifferent confirm-handling events into the loop, so the reactive resample consumes the\ndisease draws at different cadences. Pairing A against B on a shared seed measures that\ncadence artifact, not the models. So we run each model over many independent cohorts and\ncompare the means.)\n\n::: {.callout-note}\n## A = B on the bottom line, with a caveat (30 independent replications)\nOver 30 independent cohorts (`validation/validate-AB-replication.R`), A and B **agree on the\ncost axis**: the field test is cheaper by ≈ \\$47/person under both, well within Monte-Carlo\nerror. On the **health axis** they sit a hair apart and on opposite sides of zero: Approach\nB (the exact queue) puts the incremental QALY at about **−0.04** (southwest), while Approach\nA (the analytic wait) puts it at about **0.00** — right on the SE/SW boundary. The gap is\nsmall and not statistically sharp at 30 reps, but it is *directional*: A's M/M/c wait is a\ntouch optimistic under heavy saturation, so it under-states the health loss exactly where\nthe decision is closest. The convenient model and the faithful model can land on opposite\nsides of the line precisely where it matters most.\n:::\n\n### The tradeoff, stated plainly\n\nSo which to use? It depends on the regime, and the table is the guide:\n\n- **Mild contention** (the queue rarely binds): A and B agree to within noise. Prefer **A** —\n  it adds the queue with one resource and two registry events, never edits the engine, and\n  has none of B's fragile signal-and-clone machinery.\n- **Heavy contention** (the queue saturates — exactly the policy-relevant case here, where a\n  cheap test floods a fixed capacity): A's analytic wait drifts optimistic. Prefer **B** —\n  its queue is the exact emergent FIFO, and when the recommendation sits on the SE/SW\n  boundary you want the model that does not approximate the very thing the decision hinges\n  on. B is the **defensible** choice for a real recommendation; A is the fast, transparent\n  check that tells you whether contention matters at all before you pay for B.\n\n## What the decision looks like\n\nFor the Republic of SMDM, the analysis does not hand back a verdict; it hands back the\n*shape* of the choice. The field test is genuinely cheaper and genuinely reaches more women —\nbut only if the confirmatory pathway can absorb what it sends. As modelled, it cannot: the\nbottleneck converts reach into waiting, and waiting into progression. The lever that decides\nthe outcome is therefore not the test at all — it is **capacity**. Adopting the field test\n*and* expanding confirmatory throughput could keep it in the southeast; adopting it alone\nmoves it to the southwest. That coupling — between a screening choice and a downstream\nresource — is invisible to a model that treats confirmation as instantaneous or its wait as\nfixed, and it is the entire reason to reach for discrete-event simulation here.\n\n## Limitations and honest extensions\n\nThis is a deliberately spare, generic model; several real features are omitted, each of\nwhich would deepen (not reverse) the story:\n\n- **False-positive harms are costs only, not health.** A false positive here pays for a test\n  and a workup and consumes a slot, but suffers no anxiety, procedure risk, or disutility.\n  The field test's heavy false-positive burden would look worse, not better, with those on\n  the health axis.\n- **No overdiagnosis.** Every detected `S1` case here would have progressed; none is indolent\n  disease that screening finds and treats needlessly. Overdiagnosis is a central screening\n  harm and would further penalise the higher-coverage test.\n- **One bottleneck, not two.** Only confirmation is capacity-constrained; oncology treatment\n  is assumed available on demand. Real systems queue there too.\n- **Loss-to-follow-up is folded into progression.** Patients leave the queue only by\n  progressing, recovering, or dying — not by disengaging after a long wait, which in the\n  case study falls hardest on the rural women the expansion is meant to reach. An explicit\n  dropout hazard is the natural next event to add.\n- **Constant hazards, no age structure; a single lumped advanced state.** Standard\n  simplifications for a teaching model; none is load-bearing for the SE→SW result.\n\nThe point of the build was never the specific numbers; it was the mechanism — that a finite\ndownstream resource, modelled endogenously, can move a cost-effectiveness result across the\nquadrant boundary — and the two faithful ways to model it.\n\n\n# Appendix — `simmer` semantics that matter {.appendix}\n\n**Objective:** collect, in one place, the verified `simmer` 4.4.7 facts that the two designs in Part III rest on — the ones that force the shared invariant (never block the patient) and that make Approach A robust and Approach B both powerful and fragile. This appendix is the **reference card** you can return to. Every row was checked empirically against the actual code (`validation/`), and is documented at greater length in [`methodology.md`](methodology.md) §2–3. Nothing here is folklore; where a claim sounds surprising, it is because the obvious reading is wrong.\n\n## The load-bearing facts, one table\n\nThe whole document rests on a short list of primitives behaving in a specific, occasionally counter-intuitive way. Read this as the contract: if any one of these were false, the corresponding trap would *not* be a trap, or the corresponding design would *not* hold.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Verified `simmer` 4.4.7 semantics (methodology.md §2–3). The first four rows defeat the tempting fixes; the last four are what the working designs build on.\n\n|Primitive                                                                      |What it actually does (4.4.7)                                                                                                                                                         |Consequence for us                                                                                                                                    |\n|:------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------|\n|`seize()` on a full resource                                                   |**blocks the whole arrival** in the resource's FIFO queue; its hand-rolled event clock freezes                                                                                        |the core incompatibility — **never block the patient arrival** (the shared invariant of Part III)                                                     |\n|`trap()` / `wait()`                                                            |**ignored while the arrival is blocked in `seize()`** — only a renege can pull a queued arrival out                                                                                   |a queued patient cannot fire its own competing events; per-patient targeting must be string-encoded and is read only once *unblocked*                 |\n|`send()`                                                                       |a **global broadcast** to every listener; it is not addressable to one arrival                                                                                                        |per-patient signals are faked by baking the id into the name (B's `acq_<pid>` / `abandon_<pid>`); a single mismatch is silently dropped               |\n|`renege_if()` / `renege_in()`                                                  |**fires even while blocked in `seize()`**; `keep_seized` defaults **FALSE** (held resources auto-released on renege)                                                                  |the **only** lever that can pull an arrival out of a queue — B's companion uses it to abandon when the patient leaves S1                              |\n|`clone()`                                                                      |produces **distinct arrivals with independent seize ledgers** that share attribute *values* only                                                                                      |a pre-clone seize redeemed by both children **double-releases** and aborts the run — so B's companion holds no tally                                  |\n|`synchronize(wait = ...)`                                                      |`wait = FALSE`: the **first** finisher survives and re-enters the enclosing loop. `wait = TRUE`: waits for **all** siblings, last survives. Discarded clones' held resources **leak** |B relies on `wait = FALSE` so the self-clone survives; `wait = TRUE` **deadlocks** on a parked sibling                                                |\n|`rollback(n, times)`                                                           |counts **trajectory activity nodes**, not runtime events; `clone`/`synchronize` add nodes and re-inject the survivor                                                                  |if clones are present, integer targets shift — use **tag-named** targets or a `check=` predicate (a runaway otherwise)                                |\n|`get_server_count()` / `get_capacity()` / `get_queue_count()` / `get_seized()` |**callable mid-trajectory and inside a `time_to_event` sampler**; they read *live* occupancy of a real resource                                                                       |this is what makes **Approach A possible**: an endogenous wait with **no blocking** (`years_till_confirm` reads `get_server_count` vs `get_capacity`) |\n\n\n:::\n:::\n\n\nA reader who internalises only this table can reconstruct the rest. The tempting fixes that *don't* work are exactly the ones that assume one of rows 1–6 behaves *intuitively* instead of as written; A and B are exactly the designs that take rows 5–8 at face value and route around rows 1–4.\n\n## Three facts worth restating in prose\n\nA few of these are subtle enough that the one-line table cell undersells them. Each of these three is a place where careful, reasonable code is silently wrong.\n\n::: {.callout-important}\n## `send()` is global; a queued arrival is deaf to it anyway\n\nThese two facts compound. First, there is **no per-arrival signal channel** in `simmer` — `send(\"x\")` wakes *every* arrival currently in `trap(\"x\")` / `wait()`. The only way to address one patient is to encode the patient id into the signal *string* (`paste0(\"acq_\", pid)`), and a typo or attribute mismatch in that string is dropped without any error. Second, and worse for the naive fix, an arrival that is **blocked inside `seize()` does not process `trap()`/`wait()` at all** — the signal machinery is suspended for the duration of the block. So the one patient you most want to reach (the one stuck in the queue) is precisely the one a broadcast cannot wake. This is why Approach B never lets the *patient* block: only the disposable companion sits in the `seize` queue, and it is reachable via `renege_if`, not `trap`.\n:::\n\n::: {.callout-important}\n## Clones carry attribute *values*, not the seize *ledger*\n\n`clone()` is not a deep copy of process state. The children share a snapshot of attribute values, but each maintains its **own, private record of which resources it currently holds**. A resource seized *before* the `clone()` therefore sits in an ambiguous place: each child believes it can release it, but the underlying server count can only be decremented once. The second release underflows the count and `simmer` aborts mid-run (`'<resource>' not previously seized`). Because the offending release happens at an RNG-dependent moment, the crash looks *intermittent* — the most expensive kind of bug to chase. The discipline that follows (and that Approach B obeys): **never seize a shared tally on the patient before cloning, and never let a clone touch the state counters at all.** B's companion touches only the contended `confirm` resource; the patient touches only its tallies. The clone boundary is also a resource boundary, so no ledger is ever redeemed twice.\n:::\n\n::: {.callout-important}\n## Live occupancy is readable from inside a `time_to_event` sampler\n\nThis is the single permissive fact the whole of Approach A turns on, and it is easy to assume is forbidden. A `time_to_event` function in the event registry is just an R closure evaluated when the engine reschedules; nothing stops it from calling `get_server_count(env, \"confirm\")` and `get_capacity(env, \"confirm\")` on a *real* finite resource. So congestion can be read at sampling time and converted directly into a wait — longer when more slots are busy and more patients sit ahead in the FIFO position — with the patient never entering a blocking `seize`. The cap is then enforced *separately*, at fire time, by a guard that performs the real `seize` only when `get_server_count < get_capacity`. The wait is an analytic M/M/c-flavoured approximation (correct mean under saturation); the capacity is exact. Rows 1–2 forbid blocking the patient; row 8 is what lets you avoid it without abandoning a real resource.\n:::\n\n## Where each fact is exercised\n\nTo close the loop between this reference and the code, the table below points each fact at the specific design decision it underwrites — so a future maintainer touching `model10.R` (A) or `model11.R` (B) knows which invariant they are standing on.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Each verified fact, mapped to the design decision it underwrites in model10 (A) / model11 (B).\n\n|Fact                                                     |Relied on by                                                                                                   |\n|:--------------------------------------------------------|:--------------------------------------------------------------------------------------------------------------|\n|blocking `seize()` freezes the clock                     |the **shared invariant** — both A and B keep the patient out of every blocking seize                           |\n|`trap()`/`wait()` ignored while blocked; `send()` global |**B**'s per-patient `sig_acq` / `sig_abandon` string-encoded signals (the companion, not the patient, listens) |\n|`renege_if` fires from a `seize` queue                   |**B**'s abandonment: leaving S1 sends `abandon_<pid>`; a still-queued companion reneges out                    |\n|live occupancy readable in `time_to_event`               |**A**'s `years_till_confirm()` and its fire-time free-slot guard — capacity exact, no blocking                 |\n|clones have independent seize ledgers                    |the **avoidance rule**: A uses no clones at all; B's companion touches only `confirm`, never a tally           |\n|`synchronize(wait = FALSE)` first survives & re-enters   |**B**'s `clone(n = 2, self, companion) &#124;> synchronize(wait = FALSE)` — the self-clone re-enters the loop  |\n|`rollback` counts nodes, not events                      |**B**'s clone machinery is kept strictly inside the `branch` wrapper so loop targets do not shift              |\n\n\n:::\n:::\n\n\nThe pattern is worth naming. **Approach A's robustness comes from using only the permissive facts** (rows 7–8 of the first table) and the one prohibition that costs nothing (don't block the patient) — it never touches `clone`, `synchronize`, `send`, or `trap`, so none of the fragility in rows 5–6 can reach it. **Approach B is more powerful and more fragile because it uses all eight facts at once**: it accepts the blocking `seize` (row 1) but quarantines it inside a disposable companion, then threads `renege`, `send`/`trap`, `clone`, and `synchronize` together so that every one of their sharp edges (rows 2–6) is pointed away from the patient's state. That is the whole tradeoff of Part IV, reduced to which rows of this table each design chooses to depend on.\n\n## Common random numbers: the design, and its one hard limit\n\nThe variance-reduction substrate (`R/crn.R`) deserves its own note, because it has a sharp\nboundary that is easy to cross by accident.\n\n**The design.** `simmer` runs every arrival off one global RNG stream, so the textbook CRN\nmove — `set.seed()` before each arm — desynchronises the instant one arm takes a branch the\nother does not. Instead, each patient owns a **private bank** of uniforms, drawn once from a\ndeterministic per-patient seed, and every stochastic step consumes the bank by inverse-CDF\n(`qexp(u, rate)` for `rexp`, `u < p` for `runif`). Because the bank is private and fixed,\ntwo *strategies* hand patient *i* identical draws; patient *i*'s disease is bit-for-bit the\nsame in both arms until the screening *decision* diverges, so the paired difference is the\ndecision's effect with the cohort noise differenced away. The helpers `draw_exp()` /\n`draw_unif()` fall back to plain `rexp` / `runif` when no bank is armed, which is why Models\n1–6 are unchanged to the last digit.\n\n**The hard limit.** CRN aligns two *strategies within one model*. It **cannot** align two\n*different models* — Approach A and Approach B inject different confirm-handling events into\nthe loop, so the reactive resample consumes each patient's disease bank at a different\n*cadence*, and the same seed yields different draws. A shared-seed A-vs-B comparison\ntherefore measures that cadence artifact, not the models; we even see A ≠ B under a\n*null-effect* run, where the queue is inert. So A-vs-B agreement must be established by\n**independent replication** (Part IV), not by CRN — a subtle but load-bearing distinction\nwhen the two models are being compared head-to-head.\n\n::: {.callout-tip}\n## A practical gotcha in the banks\nThe per-patient seed is `CRN$seed + patient_index`, so two runs whose seeds differ by less\nthan the cohort size draw **overlapping** banks — their \"independent\" cohorts are nearly\nidentical. For genuinely independent replications (e.g. the variance demo in Model 8, or the\nA-vs-B harness), space the run seeds widely (`seed * 123457`), not by consecutive integers.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"resource-contention_files/libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"resource-contention_files/libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}